import Link from "next/link";
import { ArrowRight, BookOpen, MessageCircle, Users, UserRound, Baby, Heart, CheckCircle2, ChevronDown } from "lucide-react";
import { Page } from "@/components/SiteChrome";
import { TrustStrip, TeachingStandards, Testimonials, FinalCTA, SectionTitle } from "@/components/Shared";

const programs=[
 {icon:MessageCircle,title:"Zero to Conversational Arabic",copy:"Start from zero and build practical speaking, listening and pronunciation for real everyday conversations.",href:"/arabic-course",cta:"Explore Arabic"},
 {icon:BookOpen,title:"Online Quran Classes",copy:"Build confidence in Quran reading, Tajweed, memorization and revision with structured live guidance.",href:"/quran-classes",cta:"Explore Quran"}
];
const audiences=[[UserRound,"Adults","A clear path for beginners and returning learners."],[Baby,"Children","Patient, engaging lessons designed for younger students."],[Users,"Families","Flexible options for siblings, parents and children."],[Heart,"New Muslims","Supportive learning without assumed prior knowledge."]];
const benefits=["Qualified native Arabic-speaking teachers","Male and female teachers available","Private one-to-one and small group classes","Flexible scheduling around your routine","Structured pathways with clear goals","Live, interactive online learning"];
const faqs=[
 ["Do I need previous Arabic knowledge?","No. Our Arabic pathway is designed to welcome complete beginners as well as students returning to Arabic after a break."],
 ["Can children join?","Yes. Quran and Arabic lessons can be adapted for children, with age-appropriate pacing and teaching methods."],
 ["Are female teachers available?","Yes. We offer both male and female teachers, subject to scheduling and availability."],
 ["Are classes private or group-based?","Both options are available. You can choose private one-to-one lessons or interactive small group classes."],
 ["How do online lessons work?","Lessons are live online sessions. After your trial, we match you with a suitable teacher and agree on a schedule and learning path."],
 ["What happens in the free trial?","The trial is a chance to discuss your goals, assess your starting point, experience our teaching approach and determine the right next step."],
 ["Can I learn Quran and Arabic together?","Yes. Depending on your goals and schedule, you can study one pathway first or combine both."],
 ["How do I get started?","Book a free trial lesson. We will learn about your goals and help you choose the most suitable class format and pathway."]
];
export default function Home(){return <Page>
<section className="relative overflow-hidden"><div className="pointer-events-none absolute inset-0 grid-fade opacity-70"/><div className="shell relative grid min-h-[700px] items-center gap-12 py-16 lg:grid-cols-[1.02fr_.98fr] lg:py-24"><div><p className="eyebrow">Live online Arabic & Quran learning</p><h1 className="display mt-4">Learn Arabic.<br/><span className="text-[#0F6B4F]">Understand the Quran.</span></h1><p className="lead mt-6 max-w-2xl">Join structured live classes with qualified teachers. Choose private one-to-one lessons or interactive small groups for children and adults.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn-primary" href="/book-trial">Book Free Trial <ArrowRight className="ml-2 h-4 w-4"/></Link><a className="btn-secondary" href="#programs">Explore Programs</a></div><p className="mt-5 text-sm font-semibold text-[#6A756F]">No obligation · Personalized guidance · Flexible scheduling</p></div><div className="relative"><div className="absolute -inset-8 rounded-full bg-[#0F6B4F]/10 blur-3xl"/><div className="card relative overflow-hidden p-3"><div className="rounded-[1.5rem] bg-[#0F6B4F] p-8 text-white sm:p-10"><p className="text-sm font-bold text-white/60">ISNAD INSTITUTE</p><p className="mt-14 text-4xl font-black tracking-[-.04em] sm:text-5xl">Authentic knowledge.<br/>Modern learning.</p><div className="mt-12 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl font-black">1:1</p><p className="mt-1 text-sm text-white/70">Private learning</p></div><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl font-black">Small groups</p><p className="mt-1 text-sm text-white/70">Interactive classes</p></div><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl font-black">Arabic</p><p className="mt-1 text-sm text-white/70">Conversation first</p></div><div className="rounded-2xl bg-white/10 p-5"><p className="text-2xl font-black">Quran</p><p className="mt-1 text-sm text-white/70">Reading · Tajweed · Hifz</p></div></div></div></div></div></div></section>
<TrustStrip/>
<section className="shell py-20 sm:py-28"><SectionTitle eyebrow="For every stage" title="A learning path that meets you where you are" copy="Whether you are beginning for yourself, supporting your child or returning after years away, you can start with a clear next step."/><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{audiences.map(([Icon,t,c])=><article className="card p-6" key={t}><Icon className="h-6 w-6 text-[#0F6B4F]"/><h3 className="mt-5 text-lg font-extrabold">{t}</h3><p className="mt-2 leading-7 text-[#66716C]">{c}</p></article>)}</div></section>
<section id="programs" className="soft-section py-20 sm:py-28"><div className="shell"><SectionTitle eyebrow="Choose your journey" title="Two paths. One clear purpose." copy="Build confidence in the language, the Quran, or both—through live teaching and a structured learning experience."/><div className="mt-10 grid gap-5 lg:grid-cols-2">{programs.map(({icon:Icon,title,copy,href,cta},i)=><Link href={href} key={title} className="group card relative min-h-[360px] overflow-hidden p-8 sm:p-10"><div className="absolute right-0 top-0 h-44 w-44 rounded-bl-full bg-[#0F6B4F]/[.05] transition group-hover:scale-110"/><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#0F6B4F]/10 text-[#0F6B4F]"><Icon/></div><h3 className="mt-16 max-w-md text-3xl font-black tracking-[-.035em] text-[#17231F] sm:text-4xl">{title}</h3><p className="mt-4 max-w-lg text-lg leading-8 text-[#66716C]">{copy}</p><span className="mt-8 inline-flex items-center text-sm font-extrabold text-[#0F6B4F]">{cta}<ArrowRight className="ml-2 h-4 w-4 transition group-hover:translate-x-1"/></span></Link>)}</div></div></section>
<section className="shell py-20 sm:py-28"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><SectionTitle eyebrow="Why Isnad" title="Structured learning without the overwhelm" copy="We combine qualified teaching with modern online delivery, giving you a clear path instead of scattered lessons and guesswork."/><div className="grid gap-3">{benefits.map(x=><div key={x} className="flex items-center gap-3 rounded-2xl border border-black/[.06] bg-white px-5 py-4"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#0F6B4F]"/><span className="font-semibold text-[#46534E]">{x}</span></div>)}</div></div></section>
<section className="green-section py-20 text-white sm:py-28"><div className="shell"><p className="text-xs font-bold uppercase tracking-[.22em] text-white/55">How it works</p><h2 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.04em] sm:text-5xl">From first click to first lesson—simply.</h2><div className="mt-12 grid gap-4 md:grid-cols-4">{[["01","Book your trial","Tell us your goals and availability."],["02","Meet your teacher","Experience our live teaching approach."],["03","Get your plan","We recommend the right path and format."],["04","Start progressing","Learn consistently with feedback and support."]].map(([n,t,c])=><div key={n} className="rounded-[1.75rem] border border-white/10 bg-white/[.07] p-6"><p className="text-sm font-black text-white/45">{n}</p><h3 className="mt-8 text-xl font-extrabold">{t}</h3><p className="mt-3 leading-7 text-white/65">{c}</p></div>)}</div></div></section>
<TeachingStandards/><Testimonials/>
<section className="shell py-20 sm:py-28"><SectionTitle eyebrow="Frequently asked" title="Questions before you begin" copy="The essentials, answered clearly."/><div className="mt-10 grid gap-3">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl border border-black/[.06] bg-white p-6"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 font-extrabold text-[#27332E]">{q}<ChevronDown className="h-5 w-5 shrink-0 text-[#0F6B4F] transition group-open:rotate-180"/></summary><p className="mt-4 max-w-3xl leading-7 text-[#66716C]">{a}</p></details>)}</div></section>
<FinalCTA/>
</Page>}
